### ISSUE TITLE
MacOS Installer not showing up in OpenCore Boot Selector

### ISSUE THREAD

**Issue by vicshacks** [icaros7/OpenCore_Surface_Pro_4#12]
Hi! I have the same exact SP4 model as you listed here. I tried installing MacOS Big Sur with your EFI and this recovery image: https://archive.org/details/base-system_202102 (downloaded both DMG and CHUNKLIST and copied them into "com.apple.recovery.boot" in my USB)

When I try to boot from USB, the OC Boot selector is loaded but there's just a "Windows" option, with no way to access the MacOS installer. I haven't seen this problem discussed elsewhere and there isn't much help avaiable online so I'm opening this.
Thanks

**Comment by icaros7** [comment]
> Hide Auxiliary: Enabled (Space Bar to see that entry like recovery)
>
> on readme.md

Did you try to press space bar to showing more option?

**Comment by icaros7** [comment]
No after comment until 2022-02-05, Closing issue
