### ISSUE TITLE
Power and Volume buttons

### ISSUE THREAD

**Issue by billabongbruno** [icaros7/OpenCore_Surface_Pro_4#3]
Greetings, fellow Surface Pro 4 owner and hackintosher.

First of all, congratulations on all your work.
I just tried it out and it works great, as expected.

I have the exact same model as you.

I already had my own almost-fully functional EFI folder based on OpenCore 0.7.0 as well (obviously can't get the touch and the Wifi / BT to work, same as you).

But apart from that, there is something else that has always bothered me and that I've been trying to find a way to fix, but have been unable to.

The volume and power buttons on our Surface Pro 4 do not work, which is a shame.

I tried asking in BigSadan's repo, but alas, he is not very active anymore and got no reply.

I came across someone who had this issue too and was able to fix it, but sadly didn't go into much detail on how he did so, which is a shame.

Therefore, I came across your repo and saw that you are active in replying to the one issue that was posted and was wondering if you are willing to figure this out together.

I tried your folder in the hopes that the power button issue would be fixed, but alas, it was not either.

The link to the forum where I found the other person's issue is here:

https://www.tonymacx86.com/threads/surface-pro-4-lid-sleep-wake-power-button-and-volume-buttons.213780/

Thank you in advance for any help and once again, congratulations on your work.
I know how hard and time consuming this can be.

Best regards,
Bruno.

EDIT:

After scouring the Internet, I believe I found something.
Apparently we can go from here:
https://github.com/RehabMan/OS-X-ACPI-Keyboard

EDIT 2:
I also found this:
https://www.programmersought.com/article/9099709695/

But I am unsure on how to get that up and running.
I have no idea on how to patch it, which files need to be edited and how, seeing as we are using OpenCore.

**Comment by icaros7** [comment]
Thank you for visit my repo 😄 

First of all, I don't know how can I give you a hand with my knowledge...
Above all, I didn't anything to patch for use that buttons. In my own surface pro 4, power button & volume button working as well.

It's my little question for solve.

Q1. Is working hard reset button? (via press pwr + volUp + volDn for 5 second. it's mainbaord function.) or can use other OS?
Q2. Did you use own DSDT.aml?

**Comment by icaros7** [comment]
I'm so sorry for confusion.

On my surface pro doesn't working that button.

I haven't thinked those buttons before, so I haven't tried them.
As a result, it doesn't really work.

**Comment by icaros7** [comment]
I'm so sorry for confusion.

On my surface pro doesn't working that button.

I haven't thought to use that buttons before, so I never used them.
As a result, it doesn't really work.

I will check that link what you gave me.

**Comment by billabongbruno** [comment]
> 
> 
> Thank you for visit my repo 😄
> But, I don't know how can I a hand for you with my knowledge
> 
> I'm so sorry for confusion.
> 
> On my surface pro doesn't working that button.
> 
> I haven't thought to use that buttons before, so I never used them.
> As a result, it doesn't really work.
> 
> I will check that link what you gave me.

Hello again.

Ok, so I seem to have made some progress (or not).
I have tried to patch the DSDT using MaciASL (the most recent one from Acidanthera - https://github.com/acidanthera/MaciASL/releases), but I now come to this error:

"Dependency com.apple.iokit.IOHIDSystem fallback to com.apple.iokit.IOHIDFamily succeeded. Please fix your kext!"

And then it stops loading.

Any idea?

Or did I just not patch it right?

Best regards,
Bruno.

**Comment by icaros7** [comment]
Thank you for visit my repo 😄
But, I don't know how can I a hand for you with my knowledge

~~Above all, On my surface pro's Pwr button and Vol button are working as well~~

---

I'm so sorry for confusion.

On my surface pro doesn't working that button.

I haven't thought to use that buttons before, so I never used them.
As a result, it doesn't really work.

I will check that link what you gave me.

**Comment by icaros7** [comment]
I found SP4 buttons are control by _HID MSHW0040.

It's seem to solve via edit DSDT.aml or voodooI2C.kext...

**Comment by billabongbruno** [comment]
> 
> 
> I found SP4 buttons are control by _HID MSHW0040.
> 
> It's seem to solve via edit DSDT.aml or voodooI2C.kext...

EDIT:

I fixed it, it's all working now.
I can share the files if you want me to.

**Comment by billabongbruno** [comment]
EDIT:

I've gone ahead and saved you the trouble and I'm sharing the fix for your specific build.
All you gotta do is copy-paste into the appropriate place.

Don't forget to edit config.plist to make sure the new kext is loaded.

Thank you for the replies.

Glad I could help and that I finally was able to solve my issue (and yours).
[FIX_Volume_Power_Buttons.zip](https://github.com/icaros7/OpenCore_Surface_Pro_4/files/6630937/FIX_Volume_Power_Buttons.zip)

**Comment by billabongbruno** [comment]
FIXED with "FIX_Volume_Power_Buttons.zip"

**Comment by icaros7** [comment]
@billabongbruno Thank you for your help 😄

Now, I can use the power button via your help!

**Comment by icaros7** [comment]
This patch was pulled 42c242c

Thank you again for your hard work, it is greatly appreciated.

**Comment by icaros7** [comment]
This patch was merge at 42c242c

Thank you again for your hard work, it is greatly appreciated.

**Comment by billabongbruno** [comment]
> @billabongbruno Thank you for your help 😄
> 
> Now, I can use the power button via your help!

No worries, man.
I'm just glad I could help.

One less thing to worry about in our Surface Pro 4 Hackintoshes.

I'll see if I can convince someone to help me write a kext for the Wifi / BT (Marvell Avastar).

Someone started that a long time ago, but the project didn't follow through.

I am currently using a USB adapter (COMFAST 811 AC), but it would be sweet to get the internal board working.
