### ISSUE TITLE
VoodooI2C-2.6.5 possible? Only VoodooI2C-2.3 is working.

### ISSUE THREAD

**Issue by billabongbruno** [icaros7/OpenCore_Surface_Pro_4#4]
Hey there, once again.

So, I have been updating the kexts from all around and I came across this little minor "issue", so to speak.

I see that the VoodooI2C version used here is the 2.3.

Is there anyway to get the latest version working on this?
I have been trying, but I either don't have trackpad and keyboard or I just don't have the keyboard.

I would need to boot up into MacOS itself to see if the gestures are working, with the mix the I found, but since I can't type my password, I can't confirm this.

Anyway, the question remains.

Is it possible to use 2.6.5 and still have both the keyboard and the trackpad with gestures working?

Best regards,
Bruno.

**Comment by icaros7** [comment]
Well come back again 😃 

When I use latest voodooI2C or HID, seems to unable to use keyboard or trackpad (recognized mouse)

But you can use 2.5.x on [@bigsadan's pachted version](https://github.com/bigsadan/surface-pro-4-hackintosh/tree/master/voodooi2c/2.5.2)

I was tired-up recently, so I didn't check about diff that two kext files. (Actually, there is no problem to use right now, so I am looking for Reltek sd reader first)

in my opinion, May be get some way to get that function in that file.

Thank you for your attention about our SP4 hackintosh life.

**Comment by billabongbruno** [comment]
> Well come back again 😃
> 
> When I use latest voodooI2C or HID, seems to unable to use keyboard or trackpad (recognized mouse)
> 
> But you can use 2.5.x on [@bigsadan's pachted version](https://github.com/bigsadan/surface-pro-4-hackintosh/tree/master/voodooi2c/2.5.2)
> 
> I was tired-up recently, so I didn't check about diff that two kext files. (Actually, there is no problem to use right now, so I am looking for Reltek sd reader first)
> 
> in my opinion, May be get some way to get that function in that file.
> 
> Thank you for your attention about our SP4 hackintosh life.

Oh, I didn't know that.
Thank you.

Also, sorry for the bother.

Also, on another note...
SD card reader is fixed using the Sinetek kext.
I also have another computer that I have Hackintoshed (Nitro 5 AN-515-52) and I spent a lot of time trying to fix it and eventually I got it.

All you gotta do is add the latest version to kexts of this:
https://github.com/cholonam/Sinetek-rtsx/releases

(and of course update your config.plist accordingly)

**Comment by billabongbruno** [comment]
Also, @icaros7 , just a quick question because I got really curious.

What is the reason behind the 4 files
"SSDT-SBUS.aml"
"SSDT-SLPB.aml"
"SSDT-UIAC.aml"
"SSDT-USBW.aml"

under the ACPI folder?

They are not used in config.plist, hence I assume they are not being used.

What is their purpose?
Debugging if needed?

Best regards,
Bruno Santana.

**Comment by icaros7** [comment]
> Also, on another note...
> SD card reader is fixed using the Sinetek kext.
> I also have another computer that I have Hackintoshed (Nitro 5 AN-515-52) and I spent a lot of time trying to fix it and eventually I got it.
> 
> All you gotta do is add the latest version to kexts of this:
> https://github.com/cholonam/Sinetek-rtsx/releases

@billabongbruno Thank you for your information. I'll try that with update 0.7.0


> Also, @icaros7 , just a quick question because I got really curious.
> 
> What is the reason behind the 4 files
> "SSDT-SBUS.aml"
> "SSDT-SLPB.aml"
> "SSDT-UIAC.aml"
> "SSDT-USBW.aml"
> 
> under the ACPI folder?
> 
> They are not used in config.plist, hence I assume they are not being used.
> 
> I know what they are meant to do if used, but since they are not referenced in config.plist, they never get invoked.
> 
> What is their purpose?
> Debugging if needed?
> 
> Best regards,
> Bruno Santana.

That files are not need SP4, but include for other surface like pro 6+, book series. Because @bigsadan's OpenCore is not only for SP4, but also other surface series. So I decided to include patched file for other people who want to use :)

**Comment by billabongbruno** [comment]
> @billabongbruno Thank you for your information. I'll try that with update 0.7.0

You're most welcome, my pleasure to help.

> That files are not need SP4, but include for other surface like pro 6+, book series. Because @bigsadan's OpenCore is not only for SP4, but also other surface series. So I decided to include patched file for other people who want to use :)

Oh, Ok.
I knew that his repo (and yours) were designed for all Surface Pro devices, but that never occurred to me.

I apologize for not having thought of that beforehand.

I will have some time off on Thursday, so I will try to compare the SP's patched version of Voodoo2IC (2.5.2) with the latest 2.6.5.

I have found some info on the subject that would allow us to update to recent kexts without patching them, but instead patch the dsdt.

I don't have the link here, because I am using my phone, but once I get home again I will post it here, just so you are aware of what I'm saying.

**Comment by Giant-Li** [comment]
> > Well come back again 😃
> > When I use latest voodooI2C or HID, seems to unable to use keyboard or trackpad (recognized mouse)
> > But you can use 2.5.x on [@bigsadan's pachted version](https://github.com/bigsadan/surface-pro-4-hackintosh/tree/master/voodooi2c/2.5.2)
> > I was tired-up recently, so I didn't check about diff that two kext files. (Actually, there is no problem to use right now, so I am looking for Reltek sd reader first)
> > in my opinion, May be get some way to get that function in that file.
> > Thank you for your attention about our SP4 hackintosh life.
> 
> Oh, I didn't know that.
> Thank you.
> 
> Also, sorry for the bother.
> 
> Also, on another note...
> SD card reader is fixed using the Sinetek kext.
> I also have another computer that I have Hackintoshed (Nitro 5 AN-515-52) and I spent a lot of time trying to fix it and eventually I got it.
> 
> All you gotta do is add the latest version to kexts of this:
> https://github.com/cholonam/Sinetek-rtsx/releases
> 
> (and of course update your config.plist accordingly)

Hi, seems that the Sinetek's code wasn't design for surface. Could you please share your method how to config on surface?

**Comment by billabongbruno** [comment]
Please close this. Problem has been fixed. Also, SD card fully working.
